### ISSUE TITLE
Podium and jhiTranslate problem

### ISSUE THREAD

**Issue by rtnieuwboer** [thehyve/podium#300] opened 2021-04-08 15:26 UTC
Sometimes a user sees strings like "global.title", "requestSidebar.status.Review", "request.action.details" on her/his screen instead of the translated ones. When it does, none of the jhiTranslates look correct to me. It looks like it has nothing to do with the lang_key for that particular user, nor the language of the browser (Google Chrome/Safari). Attached a screenshot of the upper part of a page. Thanks!

![podium_bad_strings](https://user-images.githubusercontent.com/35834130/114053659-7116d880-988f-11eb-8389-4b8a30d12fef.jpg)

**Comment by gijskant** [comment] 2021-04-16 08:29
Hi @rtnieuwboer,
We noticed this issue as well and expect it to be solved in the next release that we are currently preparing. This release will mainly contain dependency updates and is expected in a couple of weeks.
Kind regards,
Gijs

**Comment by gijskant** [comment] 2021-06-11 12:06
Hi @rtnieuwboer,

The issue should have been resolved in [release 1.0.4](https://github.com/thehyve/podium/releases/tag/1.0.4).
Please note that this new release required Elasticsearch 7 to be installed. See [docs/installation.md](https://github.com/thehyve/podium/blob/dev/docs/installation.md) for the complete installation instructions.
Can you verify that the issue is gone?

Kind regards,
Gijs

**Comment by rtnieuwboer** [comment] 2021-06-21 07:50
Hi Gijs, Thanks, i have now installed 1.0.5 (updated from 1.0.1). I will let you know when some user detects it again...

**Comment by gijskant** [comment] 2021-06-24 06:54
Hi @rtnieuwboer,

We found a similar issue during testing, which is now fixed in [release 1.0.6](https://github.com/thehyve/podium/releases/tag/1.0.6).

Kind regards,
Gijs

**Closed as completed** 2021-09-13 14:45 UTC
